language: python

sudo: false

matrix:
  fast_finish: true
  include:
  - python: 3.6
    env: TEST_TARGET=default
  - python: 3.7
    env: TEST_TARGET=default
  allow_failures:
  - python: 3.7
    env: TEST_TARGET=default

before_install:
  - wget http://bit.ly/miniconda -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update conda
  - conda config --remove channels defaults --force
  - conda config --add channels conda-forge --force
  - conda create --name TEST python=$TRAVIS_PYTHON_VERSION
  - source activate TEST

# Test source distribution.
install:
  - python setup.py sdist && version=$(python setup.py --version) && pushd dist && pip install xsf_checker-${version}.tar.gz --no-deps && popd

script:
  - python -m unittest discover
